version: "3.3"
services:
  app:
    build: app
    restart: always
    networks:
      - frontend-network

  web:
    build: web
    restart: always
    ports:
      - 80:80
    networks:
      - frontend-network
volumes:
  db-data:
networks:
  frontend-network:
